apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      containers:
        - name: history-service-container
          image: gcr.io/moonlit-order-400013/history-service-image
          ports:
            - containerPort: 8006
