version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db

  postgres:
    image: postgres:14.2
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cs3219
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./assignment-backend/init-scripts:/docker-entrypoint-initdb.d

  assignment-backend:
    build:
      context: ./assignment-backend
      dockerfile: Dockerfile
    container_name: assignment-backend
    ports:
      - 5000:5000
    env_file:
      - ./assignment-backend/.env
    volumes:
      - ./assignment-backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - postgres

  assignment-frontend:
    build:
      context: ./assignment-frontend
      dockerfile: Dockerfile
    container_name: assignment-frontend
    ports:
      - 3000:3000
    volumes:
      - ./assignment-frontend/src:/app/src
      - /app/node_modules
    tty: true
    depends_on:
      - assignment-backend

volumes:
  data:
  logs:
  postgres_data:
    driver: local
