import { doc, getFirestore, serverTimestamp, setDoc } from 'firebase/firestore';
import React, { useEffect, useState } from 'react';
import ChatRoom from './ChatRoom';
import Loading from './Loading';

/*
    Call this component to display chat component on screen
*/

interface ChatComponentProps {
    sessionId: string | string[];
}

const ChatComponent: React.FC<ChatComponentProps> = (props: any) => {
    const { sessionId } = props;
    const matchToken = sessionId;

    console.log(sessionId);

    // data we need for each and every user coming through here
    // 1. Their matchToken
    // 2. their userId
    // 3. Their username 
    // 4. PhotoId if possible (not necessary)
    const [docRef, setDocRef] = useState({});
    const [userId, setUserId] = useState("");

    useEffect(() => {
        // run this pre-load logic once to load matchToken into the user's document
        // this should be under YiTing's logic whereby the token will be generated by him
        // and we will get the two matched users to only update this specific subcollection under matched tokens
        const db = getFirestore();

        const addData = async () => {
            await setDoc(doc(db, "matched-tokens", matchToken), {
                matchToken: matchToken,
                createdAt: serverTimestamp()
            })
                .then(() => {
                    console.log("Document successfully written!");
                    setDocRef(doc(db, "matched-tokens", matchToken));
                })
                .catch(error => { console.error("Error adding document: ", error); });
        }
        addData();

        // get the current userid from the localstorage, which was set upon login
        const userId = localStorage.getItem("userid");
        if (userId != null) {
            setUserId(userId);
        }
    }, []);

    const renderChatComponent = () => {
        return (
            <div className="text-center max-w-screen-md mx-auto">
                {/* <h1>ChatComponent</h1> */}
                {/* Call the other chatComponents here */}
                <section>
                    {(userId && docRef) ? <ChatRoom docRef={docRef} userId={userId}/> : <Loading />}
                </section>
            </div>
        )
    }

    return (
        renderChatComponent()
    )
}

export default ChatComponent;