apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
spec:
  type: NodePort
  ports:
    - port: 8004
      targetPort: 8004
      nodePort: 30100
  selector:
    app: collaboration-service
