apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service-container
          image: gcr.io/moonlit-order-400013/question-service-image
          ports:
            - containerPort: 8001
