apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
    spec:
      containers:
        - name: kafka-service
          image: wurstmeister/kafka:2.11-1.1.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service.default.svc.cluster.local:2181
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: 'true' 
            - name: KAFKA_CREATE_TOPICS
              value: "topic-test:1:1"
            - name: NODE_ENV
              value: "production"
            - name: KAFKA_HOST
              value: "kafka-service.default.svc.cluster.local:9092"
          volumeMounts:
            - name: kafka-data
              mountPath: /kafka/data
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data-pvc
