apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaking-service
  template:
    metadata:
      labels:
        app: matchmaking-service
    spec:
      containers:
      - name: matchmaking-service
        image: gcr.io/moonlit-order-400013/matchmaking-service-image
        ports:
        - containerPort: 8002
        env:
        - name: NODE_ENV
          value: "production"
        - name: AMQP_HOST
          value: "amqp://amqp-service.default.svc.cluster.local:5672"
        - name: KAFKA_HOST
          value: "kafka-service.default.svc.cluster.local:9092"