apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-service
  template:
    metadata:
      labels:
        app: zookeeper-service
    spec:
      containers:
      - name: zookeeper-service
        image: wurstmeister/zookeeper:latest
        ports:
        - containerPort: 2181