kafka:
  image:
    repository: wurstmeister/kafka
    tag: 2.11-1.1.1
  containerPort: 9092
  zookeeperConnect: zookeeper-service.default.svc.cluster.local:2181
  # autoCreateTopics: false
  deleteTopicEnable: true
  kraft:
    enabled: false 
  createTopics:
    - name: session-information
      partitions: 1
      replicationFactor: 1
  configurationOverrides:
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: kafka-service
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: 'true'
    - name: KAFKA_DELETE_TOPIC_ENABLE
      value: 'true'
    - name: NODE_ENV
      value: "production"


persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  enabled: true
  type: ClusterIP
  port: 9092


