name: CD Pipeline

on:
  push:
    branches:
      - master
      - deployment
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Get Node.js version
        run: |
          echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> "$GITHUB_ENV"

      - name: Generate deployment package
        run: |
          zip -r frontend.zip frontend

      - name: Deploy Frontend
        uses: google-github-actions/deploy-appengine@v1
        with:
          credentials: ${{ secrets.YOUR_GCP_CREDENTIALS_SECRET }}
          project_id: moonlit-order-400013
          version: ${{ github.run_number }} 
          config: 'service.yaml' # Specify your App Engine configuration file
          source: './frontend.zip' # Path to your deployment package




